version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_server
    ports:
      - "5200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "dbnodejs"
    volumes:
      - vol-mysql-nodejs09:/var/lib/mysql
    networks:
      - net-cursonodejs09

  redis:
    image: redis:6.0.5-alpine
    container_name: redis_server
    command: redis-server --requirepass todovale
    ports:
      - "6379:6379"
    restart: always

  logstash:
    image: logstash:7.8.1
    container_name: logstash
    volumes:
      - ./elk_config/logging.conf:/usr/share/logstash/pipeline/logging.conf
      - ./elk_config/logstash.yaml:/usr/share/logstash/config/logstash.yml
    ports:
      - 1514:1514/udp
      - 1515:1515
      - 1515:1515/udp
    networks:
      - net-cursonodejs09

  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - vol-elasticsearch:/usr/share/elasticsearch/data
      - ./elk_config/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      discovery.type: single-node
    networks:
      - net-cursonodejs09

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    volumes:
      - ./elk_config/kibana.yaml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - net-cursonodejs09

  sonarqube:
    image: sonarqube:8-community
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9092:9092

  locust-master:
    build:
      context: .
      dockerfile: locust/Dockerfile
    container_name: master
    ports:
      - "8089:8089"
    command: "--host=https://4c52-38-25-16-207.ngrok.io --master"

  locust-slave:
    build:
      context: .
      dockerfile: locust/Dockerfile
    command: "--host=https://4c52-38-25-16-207.ngrok.io --master-host=locust-master --slave"
volumes:
  vol-mysql-nodejs09:
  vol-elasticsearch:

networks:
  net-cursonodejs09:
